name: Generate quest list
on:
  push:
    branches:
      - master

jobs:
  generate-quest-list:
    name: Generate quest list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: node .github/generate-quest-list.mjs
      - uses: actions/upload-artifact@v2
        with:
          name: quest-list.csv
          path: ./quest-list.csv
