name: Generate quest list
on:
  push:
    branches:
      - master

jobs:
  generate-quest-list:
    name: Generate quest list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - run: node .github/generate-quest-list.mjs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update quest list
